Connecting to Arduino...
Arduino connected...
Uno:!
Unrecognized command: 
Uno:Running
Uno:!ping
Pi:Success
Uno:Success
Uno:RPi_check done
Uno:!target_coords
Pi:1 1280

Uno:!target_coords
Pi:1 1280

Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Traceback (most recent call last):
  File "serial_manager.py", line 95, in <module>
    result = command_list[tokens[0]](tokens[1:])
  File "serial_manager.py", line 31, in target_coords
    subprocess.call(['raspistill','-o','out.jpg','-t','1','-w','1280','-h','960'])
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1301, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

Uno:1,1280
Uno:!target_coords
Pi:1 1280

Uno:!target_coords
Traceback (most recent call last):
  File "serial_manager.py", line 95, in <module>
    result = command_list[tokens[0]](tokens[1:])
  File "serial_manager.py", line 31, in target_coords
    subprocess.call(['raspistill','-o','out.jpg','-t','1','-w','1280','-h','960'])
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1301, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

Uno:!target_coords
Pi:1 1280

Uno:!target_coords
Pi:1 1280

Uno:!target_coords
Pi:1 1280

Uno:1,1280
Uno:!target_coords
Traceback (most recent call last):
  File "serial_manager.py", line 95, in <module>
    result = command_list[tokens[0]](tokens[1:])
  File "serial_manager.py", line 31, in target_coords
    subprocess.call(['raspistill','-o','out.jpg','-t','1','-w','1280','-h','960'])
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1301, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt

Uno:1,1280
